services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reading-tracker
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    labels:
      traefik.enable: "true"
      traefik.http.routers.app.rule: Host(`${DOMAIN?DOMAIN not set}`)
      traefik.http.routers.app.entrypoints: websecure
      traefik.http.routers.app.tls: "true"
      traefik.http.routers.app.tls.certresolver: letsencrypt
      traefik.http.services.app.loadbalancer.server.port: "3002"
